здесь сильные модели проверяют ответы тестируемых моделей на правильность.
реализовано сравнение эталонного ответа из бенчмарка и ответа модели, потому что метрики типа f1 не всегда помогают в задачах типа qa и summarization.

llm as a judge

In [1]:
import pandas as pd
from tqdm import tqdm
import json

загрузка датасета

In [2]:
dataset_path = "/kaggle/input/datasets/yumiasakura/test-800/test_results (1).csv"
df = pd.read_csv(dataset_path)

print(df.head())

print(df.info())

    task_id benchmark task_type dataset_split  \
0  bbh_1263       bbh        qa          test
1  bbh_3951       bbh        qa          test
2  bbh_6199       bbh        qa          test
3  bbh_6080       bbh        qa          test
4    bbh_96       bbh        qa          test

                                            question context options  \
0  "It is not always easy to grasp who is consumi...     NaN     NaN
1  On the table, you see two burgundy mugs, one b...     NaN     NaN
2  Question: Rashida tells the truth. Jim says Ra...     NaN     NaN
3  Question: Phoebe tells the truth. Jamey says P...     NaN     NaN
4                  False or ( False ) or not True is     NaN     NaN

  correct_answer subtask                                          metadata  \
0          valid     NaN                 {'task_name': 'formal_fallacies'}
1            (C)     NaN  {'task_name': 'reasoning_about_colored_objects'}
2             No     NaN                      {'task_name': 'web_of_lies'}
3             No     NaN                      {'task_name': 'web_of_lies'}
4          False     NaN              {'task_name': 'boolean_expressions'}

                                           Qwen-7b_1  Qwen-7b_1_result  \
0  Answer:\n\nThe argument is invalid. The premis...               NaN
1  (R) seventeen\n(S) eighteen\n(T) nineteen\n(U)...               NaN
2                        A:\n\nVina tells the truth.               NaN
3                        A:\n\nVina tells the truth.               NaN
4                                     Answer:\nFalse               NaN

                                           Qwen-7b_2  Qwen-7b_2_result  \
0  Answer:\n\nThe argument is invalid. The premis...               NaN
1  (R) seventeen\n(S) eighteen\n(T) nineteen\n(U)...               NaN
2                        A:\n\nVina tells the truth.               NaN
3                        A:\n\nVina tells the truth.               NaN
4                                     Answer:\nFalse               NaN

                                           Qwen-7b_3  Qwen-7b_3_result
0  Answer:\n\nThe argument is invalid. The premis...               NaN
1  (R) seventeen\n(S) eighteen\n(T) nineteen\n(U)...               NaN
2                        A:\n\nVina tells the truth.               NaN
3                        A:\n\nVina tells the truth.               NaN
4                                     Answer:\nFalse               NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   task_id           800 non-null    object
 1   benchmark         800 non-null    object
 2   task_type         800 non-null    object
 3   dataset_split     800 non-null    object
 4   question          700 non-null    object
 5   context           100 non-null    object
 6   options           400 non-null    object
 7   correct_answer    800 non-null    object
 8   subtask           39 non-null     object
 9   metadata          100 non-null    object
 10  Qwen-7b_1         796 non-null    object
 11  Qwen-7b_1_result  0 non-null      float64
 12  Qwen-7b_2         796 non-null    object
 13  Qwen-7b_2_result  0 non-null      float64
 14  Qwen-7b_3         796 non-null    object
 15  Qwen-7b_3_result  0 non-null      float64
dtypes: float64(3), object(13)
memory usage: 100.1+ KB
None

In [31]:
#df['task_type'] = df['task_type'].replace('multiple_choice', 'qa')

In [3]:
df.head()

,task_id,benchmark,task_type,dataset_split,question,context,options,correct_answer,subtask,metadata,Qwen-7b_1,Qwen-7b_1_result,Qwen-7b_2,Qwen-7b_2_result,Qwen-7b_3,Qwen-7b_3_result
0,bbh_1263,bbh,qa,test,"""It is not always easy to grasp who is consumi...",NaN,NaN,valid,NaN,{'task_name': 'formal_fallacies'},Answer:\n\nThe argument is invalid. The premis...,NaN,Answer:\n\nThe argument is invalid. The premis...,NaN,Answer:\n\nThe argument is invalid. The premis...,NaN
1,bbh_3951,bbh,qa,test,"On the table, you see two burgundy mugs, one b...",NaN,NaN,(C),NaN,{'task_name': 'reasoning_about_colored_objects'},(R) seventeen\n(S) eighteen\n(T) nineteen\n(U)...,NaN,(R) seventeen\n(S) eighteen\n(T) nineteen\n(U)...,NaN,(R) seventeen\n(S) eighteen\n(T) nineteen\n(U)...,NaN
2,bbh_6199,bbh,qa,test,Question: Rashida tells the truth. Jim says Ra...,NaN,NaN,No,NaN,{'task_name': 'web_of_lies'},A:\n\nVina tells the truth.,NaN,A:\n\nVina tells the truth.,NaN,A:\n\nVina tells the truth.,NaN
3,bbh_6080,bbh,qa,test,Question: Phoebe tells the truth. Jamey says P...,NaN,NaN,No,NaN,{'task_name': 'web_of_lies'},A:\n\nVina tells the truth.,NaN,A:\n\nVina tells the truth.,NaN,A:\n\nVina tells the truth.,NaN
4,bbh_96,bbh,qa,test,False or ( False ) or not True is,NaN,NaN,False,NaN,{'task_name': 'boolean_expressions'},Answer:\nFalse,NaN,Answer:\nFalse,NaN,Answer:\nFalse,NaN

оценивание результатов

In [47]:
def evaluate_answer(row, pred):

    task = row["task_type"]
    gold = row["correct_answer"]
    benchmark = row["benchmark"]
    question = row["question"]
    context = row["context"]

    if task == "multiple_choice" or task == "fact_verification":
        if benchmark == "hellaswag" or benchmark == "hover" or benchmark == "fever" or benchmark == "mmlu":
            if benchmark == "mmlu":
                pred = pred[7:10]
            return check_correct_mc(row, pred)
        else:

            pred_option = extract_choice(pred)
            return pred_option == gold

    elif task == "qa":
        #if extract_match(pred, gold):
            #return True
        if benchmark == "halueval" or benchmark == "truthfulqa" or benchmark == "bbh":
            f1_metric = f1_score(pred, gold)
            #print(f1_metric)
            if check_correct_mc(row, pred):
                return True
            elif f1_metric>=0.7:
                return True
            else: 
                verdict_llm = llm_judge_qa(question, gold, pred, judge_model, judge_tokenizer)
                if verdict_llm == True:
                    return True
                else:
                    return False
                	
    elif task == "summarization":
        cosine_similarity = semantic_match(pred, gold)
        rouge_scores = compute_rouge(pred, gold)
        r1 = rouge_scores["rouge1"]
        r2 = rouge_scores["rouge2"]
        rL = rouge_scores["rougeL"]
        #print(cosine_similarity)
        if rL>=0.35 or (r1>=0.45 and r2>=0.2):
            return True
        elif (rL>=0.2) or (r1>=0.3):
            verdict_llm = llm_judge_summary(question, context, gold, pred, judge_model, judge_tokenizer)
            if verdict_llm  == True:
                return True
        elif cosine_similarity>=0.7:
            return True
        elif cosine_similarity>=0.3 and cosine_similarity<0.7:
            verdict_llm = llm_judge_summary(question, context, gold, pred, judge_model, judge_tokenizer)
            if verdict_llm  == True:
                return True
            else:
                return False
        else: 
            return False


    return False

In [5]:
# Проверка корректности ответа для задачи mc

def check_correct_mc(row, pred):

    if row["correct_answer"] is None:
        return None

    gt = str(row["correct_answer"]).lower()
    pred = pred.lower()
    #print(gt in pred)

    return gt in pred

In [53]:
df["Qwen-7b_1"].isna().sum()

np.int64(4)

In [54]:
pd.concat([df.iloc[170:185]])

,task_id,benchmark,task_type,dataset_split,question,context,options,correct_answer,subtask,metadata,Qwen-7b_1,Qwen-7b_1_result,Qwen-7b_2,Qwen-7b_2_result,Qwen-7b_3,Qwen-7b_3_result
170,dailymail_8318,dailymail,summarization,validation,NaN,Evidence: This is a picture of the stolen Budd...,NaN,Villagers say relic is their 'ancestral patria...,NaN,NaN,Summary:\n\nChinese villagers are demanding th...,False,Summary:\n\nChinese villagers are demanding th...,NaN,Summary:\n\nChinese villagers are demanding th...,NaN
171,dailymail_6385,dailymail,summarization,validation,NaN,Marine biologist: Diane Cowan has worked with ...,NaN,"Diane Cowan, 54, has been stuck on Friendship ...",NaN,NaN,Summary:\n\nMarine biologist Diane Cowan has b...,True,Summary:\n\nMarine biologist Diane Cowan has b...,NaN,Summary:\n\nMarine biologist Diane Cowan has b...,NaN
172,dailymail_4209,dailymail,summarization,validation,NaN,When England crashed out of the last global li...,NaN,England face Afghanistan with more to lose tha...,NaN,NaN,The England cricket team is facing a final mat...,False,The England cricket team is facing a final mat...,NaN,The England cricket team is facing a final mat...,NaN
173,dailymail_10159,dailymail,summarization,validation,NaN,For most of her life young Queensland woman Sa...,NaN,"US father never gave up on daughter,Savanna To...",NaN,NaN,"The article is about Samantha Geldenhuys, who ...",False,"The article is about Samantha Geldenhuys, who ...",NaN,"The article is about Samantha Geldenhuys, who ...",NaN
174,dailymail_8949,dailymail,summarization,validation,NaN,Remembered in history by some as a murderous t...,NaN,Mr Cumberbatch and Richard III are second cous...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,dailymail_5687,dailymail,summarization,validation,NaN,A Chinese family was kicked off a Cathay Pacif...,NaN,Plane sat at its gate in Bangkok while father ...,NaN,NaN,The article reports on a Chinese family who we...,NaN,The article reports on a Chinese family who we...,NaN,The article reports on a Chinese family who we...,NaN
176,dailymail_6613,dailymail,summarization,validation,NaN,A watchdog has cleared officers over the case ...,NaN,Hamzah Khan's decomposed body found in cot two...,NaN,NaN,Summary:\n\nA watchdog has cleared West Yorksh...,NaN,Summary:\n\nA watchdog has cleared West Yorksh...,NaN,Summary:\n\nA watchdog has cleared West Yorksh...,NaN
177,dailymail_63,dailymail,summarization,validation,NaN,"(CNN)The Rev. Fred Craddock, the pulpit giant ...",NaN,Fred Craddock revolutionized art of preaching ...,NaN,NaN,"The Rev. Fred Craddock, a renowned preacher, h...",NaN,"The Rev. Fred Craddock, a renowned preacher, h...",NaN,"The Rev. Fred Craddock, a renowned preacher, h...",NaN
178,dailymail_10193,dailymail,summarization,validation,NaN,Enjoy a dip in the sea and you risk picking up...,NaN,Swimmers and surfers are most at risk of catch...,NaN,NaN,Summary:\n\nA study by the University of Exete...,NaN,Summary:\n\nA study by the University of Exete...,NaN,Summary:\n\nA study by the University of Exete...,NaN
179,dailymail_6423,dailymail,summarization,validation,NaN,A 23-year-old woman allegedly caught driving w...,NaN,Bianca Micallef was stopped by police on Tuesd...,NaN,NaN,"A 23-year-old woman, Bianca Micallef, has been...",NaN,"A 23-year-old woman, Bianca Micallef, has been...",NaN,"A 23-year-old woman, Bianca Micallef, has been...",NaN
180,dailymail_10158,dailymail,summarization,validation,NaN,Poole Town manager Tom Killick decided to watc...,NaN,Tom Killick watched his side's win over Cambri...,NaN,NaN,Poole Town manager Tom Killick was banned from...,NaN,Poole Town manager Tom Killick was banned from...,NaN,Poole Town manager Tom Killick was banned from...,NaN
181,dailymail_6458,dailymail,summarization,validation,NaN,Game show viewers were left outraged by a buzz...,NaN,Contestants Matt Molloy and Mary Ryan were fac...,NaN,NaN,The article is about a Family Feud game show i...,NaN,The article is about a Family Feud game show i...,NaN,The article is about a Family Feud game show i...,NaN
182,dailymail_1530,dailymail,summarization,validation,NaN,Europa League broadcasters ITV have pulled off...,NaN,Everton face Dynamo Kiev at Goodison Park on T...,NaN,NaN,"The article reports that Leighton Baines, an i...",NaN,"The article reports that Leighton Baines, an i...",NaN,"The article reports that Leighton Baines, an i...",NaN
183,dailymail_7439,dailymail,summarization,validation,NaN,"What have Fearne Cotton, Denise van Outen, Jo ...",NaN,Stylish celeb mums support charity campaign by...,NaN,NaN,"Summary:\n\nCelebrities such as Fearne Cotton,...",NaN,"Summary:\n\nCelebrities such as Fearne Cotton,...",NaN,"Summary:\n\nCelebrities such as Fearne Cotton,...",NaN
184,dailymail_9648,dailymail,summarization,validation,NaN,"Alcohol often goes hand in hand with violence,...",NaN,Drunk man in Sri Lankan national park decided ...,NaN,NaN,The article describes a drunk man in Sri Lanka...,NaN,The article describes a drunk man in Sri Lanka...,NaN,The article describes a drunk man in Sri Lanka...,NaN

In [55]:
df["Qwen-7b_1"] = df["Qwen-7b_1"].fillna("")

In [56]:
df["Qwen-7b_1"].isna().sum()

np.int64(0)

In [57]:
df["Qwen-7b_2"].isna().sum()

np.int64(4)

In [58]:
df["Qwen-7b_3"].isna().sum()

np.int64(4)

In [59]:
df["Qwen-7b_2"] = df["Qwen-7b_3"].fillna("")
df["Qwen-7b_3"] = df["Qwen-7b_3"].fillna("")

In [6]:
from collections import Counter
import re
import string

In [7]:
def extract_choice(text):
    match = re.search(r'\b([A-D])\b', text)
    if match:
        return match.group(1)
    match = re.search(r'\b([0-3])\b', text)
    if match:
        return match.group(1)
    return None

In [32]:
s = 5
if s is float or s is int:
    print(7)

In [43]:
def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

In [44]:
def normalize(text):
    text = str(text)
    if is_number(text) == False:
        text = text.lower()
    text = re.sub(r'\b(a|an|the)\b', ' ', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = " ".join(text.split())

    return text

In [42]:
normalize(8)

'8'

In [9]:
# Проверка корректности ответа для задачи qa

def f1_score(pred, gold):

    pred_tokens = normalize(pred).split()
    gold_tokens = normalize(gold).split()
    #print(pred_tokens)
    #print(gold_tokens)
    if len(pred_tokens)>0:
        if pred_tokens[0]=="answer":
            pred_tokens = pred_tokens[1:]

    common = Counter(pred_tokens) & Counter(gold_tokens)
    num_same = sum(common.values())

    if num_same == 0:
        return 0

    precision = num_same / len(pred_tokens)
    recall = num_same / len(gold_tokens)
    
    return 2 * precision * recall / (precision + recall)

llm as a judge 

Llama 3-7b - хорошо следует инструкциям из промпта, дает стабильные оценки

In [10]:
def build_judge_prompt_qa(question, correct_answer, model_answer):

    prompt = f"""
You are a strict evaluator of question answering systems.

Your task is to determine whether the model answer is correct.

Question:
{question}

Ground truth answer:
{correct_answer}

Model answer:
{model_answer}

Rules:
- Answer YES only if the meaning is clearly the same.
- Minor wording differences are allowed.
- Answer NO if there is any contradiction, missing key info, or wrong facts.
- Be strict.

Reply with only one word: YES or NO.
Do not explain.
"""

    return prompt

In [11]:
def generate_judge_answer(prompt, judge_model, judge_tokenizer):

    messages = [
        {"role": "system", "content": "You are a strict and precise judge."},
        {"role": "user", "content": prompt}
    ]

    input_ids = judge_tokenizer.apply_chat_template(
        messages,
        return_tensors="pt"
    ).to(judge_model.device)

    with torch.no_grad():
        output = judge_model.generate(
        **input_ids,   
        max_new_tokens=30,
        temperature=0.0,
        do_sample=False,
        pad_token_id=judge_tokenizer.eos_token_id
        )

    decoded = judge_tokenizer.decode(output[0], skip_special_tokens=True)
    #print(decoded)

    # берём только сгенерированную часть
    response = decoded.split("assistant")[-1].strip()

    return response

In [12]:
def llm_judge_qa(question, correct_answer, model_answer, judge_model, judge_tokenizer):

    prompt = build_judge_prompt_qa(
        question,
        correct_answer,
        model_answer
    )
    #print("PROMPT ", prompt)

    raw_output = generate_judge_answer(
        prompt,
        judge_model,
        judge_tokenizer
    )
    #print("RAW_OUTPUT ", raw_output)

    result = parse_judge_output(raw_output)
    
    #print("RESULT ", result)

    return result, raw_output

In [13]:
def llm_judge_summary(question, context, correct_answer, model_answer, judge_model, judge_tokenizer):
                     
    prompt = build_judge_prompt_sum(
        question,
        context,
        correct_answer,
        model_answer
    )

    raw = generate_judge_answer(
        prompt, 
        judge_model,
        judge_tokenizer
    )
    
    #print(raw)
    return parse_judge_output(raw), raw

In [14]:
def build_judge_prompt_sum(question, context, correct_answer, model_answer):

    prompt = f"""
You are an expert evaluator of summarization systems.

Evaluate the model summary based on the document and the reference summary.

Question:
{question}

Document:
{context}

Reference summary:
{correct_answer}

Model summary:
{model_answer}

Evaluate the model summary on the following criteria:

1. Faithfulness (no hallucinations, all facts supported by the document)
2. Correctness (facts match the reference summary)
3. Coverage (important information is included)
4. Conciseness (no unnecessary details)

Give your final verdict:

- YES → if the summary is overall correct and faithful
- NO → if it contains hallucinations or major errors

Be strict.

Reply with only one word: YES or NO.
Do not explain.
"""
    return prompt

In [15]:
def parse_judge_output(text):

    text = text.strip().upper()

    if text.startswith("YES"):
        return True
    if text.startswith("NO"):
        return False

    return None

метрика семантическая схожесть

In [16]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
model_SentenceTransformer = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [18]:
def semantic_match(pred, gold):

    emb = model_SentenceTransformer.encode([pred, gold])

    sim = cosine_similarity([emb[0]], [emb[1]])[0][0]

    return sim

загрузка модели для подхода llm as a judge

In [2]:
!pip install -U bitsandbytes>=0.46.1

In [19]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

In [20]:
from huggingface_hub import login

login("hf_LOGIN")

In [21]:
global judge_tokenizer
global judge_model

In [22]:
model_name = "meta-llama/Meta-Llama-3-8B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

judge_tokenizer = AutoTokenizer.from_pretrained(model_name, token=True)
judge_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    token=True
)
judge_tokenizer.pad_token = judge_tokenizer.eos_token

config.json:   0%|          | 0.00/654 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/73.0 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

метрика rouge для summarization

In [23]:
from rouge_score import rouge_scorer

In [24]:
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'],use_stemmer=True)

def compute_rouge(pred, gold):
    scores = scorer.score(gold, pred)

    return {
        "rouge1": scores["rouge1"].fmeasure,
        "rouge2": scores["rouge2"].fmeasure,
        "rougeL": scores["rougeL"].fmeasure,
    }

метрика BERTscore для суммаризации и длинных ответов qa

In [41]:
!pip install bert_score

Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.9.0+cu126)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.3.3)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (5.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert_score) (4.67.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert_score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert_score) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert_score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert_score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert_score) (2025.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.5.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (1.4.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (3.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (2026.1.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert_score) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert_score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert_score) (3.0.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers>=3.0.0->bert_score) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score) (0.16.0)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 2.0 MB/s eta 0:00:00
Installing collected packages: bert_score
Successfully installed bert_score-0.3.13

In [45]:
from bert_score import score as bertscore

In [46]:
def compute_bertscore(pred, gold):
    P, R, F1 = bertscore(
        [pred],
        [gold],
        lang="en",   # важно для CNN/DailyMail и большинства QA
        rescale_with_baseline=True
    )
    return float(F1[0])

оценка ответов

In [25]:
attempt = 3

In [62]:
results = []
k = 0
for i in range(1, attempt+1):
    answer_col = f"Qwen-7b_{i}"
    result_col = f"Qwen-7b_{i}_result"
    
    for idx, row in tqdm(df.iterrows(), total=len(df)):
        
        answer = row[answer_col]
        #k+=1
        #if k>170:
            #print(answer)
        is_correct = evaluate_answer(row, answer)
        #print("IS CORRECT", is_correct)
       
        df.at[idx, result_col] = is_correct

100%|██████████| 800/800 [07:02<00:00,  1.89it/s]
  0%|          | 0/800 [00:00<?, ?it/s]/tmp/ipykernel_118/1930262150.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, result_col] = is_correct
100%|██████████| 800/800 [07:03<00:00,  1.89it/s]
  0%|          | 0/800 [00:00<?, ?it/s]/tmp/ipykernel_118/1930262150.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, result_col] = is_correct
100%|██████████| 800/800 [07:03<00:00,  1.89it/s]

In [30]:
print(df[["correct_answer", "Qwen-7b_1"]])

                                       correct_answer  \
0   Zully Broussard decided to give a kidney to a ...
1   The 20th MLS season begins this weekend .\nLea...
2   Bafetimbi Gomis collapses within 10 minutes of...
3   Rory McIlroy throws club into water at WGC Cad...
4   Cayman Naib, 13, hasn't been heard from since ...
5   Ruben Navarrette: Schilling deserves praise fo...
6   Two American women arrested for carving initia...
7   It will be a first time for the tour stateside...
8   A jihadist group claims responsibility in an a...
9   Alleged incident happened in match at St James...
10  This page includes the show Transcript .\nUse ...
11  The abducted workers were seized in an attack ...
12  Wichita, Kansas, high school students surprise...
13  Comic book artist Norman Lee went missing in t...
14  This page includes the show Transcript .\nUse ...
15  Jeff Goldblum set to reprise his role in "Inde...
16  Walter Mondale was released from the Mayo Clin...
17  A man in suburban Boston is selling snow onlin...
18  Jina Krause-Vilmar: On International Women's D...
19  Real Madrid slump to defeat against Athletic B...

                                            Qwen-7b_1
0   Summary:\n\nZully Broussard, a woman who donat...
1   The MLS has progressed significantly since its...
2   French striker Bafetimbi Gomis, who has a hist...
3   Rory McIlroy, the world's reigning No. 1 golfe...
4   The article is about a missing eighth-grade st...
5   Summary:\n\nCurt Schilling, a former Major Lea...
6   The article reports on two American women who ...
7   Summary:\n\nPrince and 3rdEyeGirl will bring t...
8   Summary:\n\nA shooting at a bar in Bamako, Mal...
9   Manchester United defender Jonny Evans and New...
10  The article discusses various news stories fro...
11  The article reports that nine foreign workers,...
12  The article is about a high school principal, ...
13  The search for a missing comic book artist, No...
14  The article discusses the upcoming coverage of...
15  Jessie Usher, the lead of Starz's series "Surv...
16  The article reports that former Vice President...
17  Summary:\n\nA man in Massachusetts is selling ...
18  The article discusses the challenges faced by ...
19  Real Madrid lost 1-0 to Athletic Bilbao, poten...

In [31]:
pred = df["correct_answer"][1]
gold = df["Qwen-7b_1"][1]
print(pred)
print(gold)

The 20th MLS season begins this weekend .
League has changed dramatically since its inception in 1996 .
Some question whether rules regarding salary caps and transfers need to change .
The MLS has progressed significantly since its inception in 1996, with higher attendances, more teams, and a new domestic TV and media rights deal worth $700 million over eight years. The league has also attracted more prominent stars

In [32]:
semantic_match(pred, gold)

np.float32(0.5730698)

In [33]:
f1_score(pred, gold)

0.2903225806451613

In [34]:
compute_rouge(pred, gold)

{'rouge1': 0.30303030303030304,
 'rouge2': 0.15625,
 'rougeL': 0.2727272727272727}

In [47]:
compute_bertscore(pred, gold)

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

0.24950893223285675

accuracy по бенчмаркам

In [63]:
for i in range(1, attempt+1):
    result_col = f"Qwen-7b_{i}_result"
    accuracy = df.groupby("benchmark")[result_col].mean()

    print(accuracy)

benchmark
bbh           0.43
dailymail     0.34
fever          0.5
halueval       0.3
hellaswag     0.18
hover         0.52
mmlu          0.29
truthfulqa    0.16
Name: Qwen-7b_1_result, dtype: object
benchmark
bbh           0.43
dailymail     0.34
fever          0.5
halueval       0.3
hellaswag     0.18
hover         0.52
mmlu          0.29
truthfulqa    0.16
Name: Qwen-7b_2_result, dtype: object
benchmark
bbh           0.43
dailymail     0.34
fever          0.5
halueval       0.3
hellaswag     0.18
hover         0.52
mmlu          0.29
truthfulqa    0.16
Name: Qwen-7b_3_result, dtype: object

In [58]:
df.to_csv(
    "/kaggle/working/truthfulqa_hellaswag_qwen_results.csv",
    index=False
)